#! /bin/sh

# prepare persistence
mkdir -p /usr/lib/tor
chown tor /usr/lib/tor

torip=$(uci get network.tor.ipaddr)

/etc/init.d/tor enable
/etc/init.d/tor start

cat >>/etc/tor/torrc <<EOF
TransListenAddress $torip
DNSListenAddress $torip
EOF
