#!/bin/sh
set -euf
. /usr/lib/firstrun.sh
itf=eth0

clear_interface_config $itf

uci batch <<EOF
delete network.wan
set network.wan=interface
set network.wan.ifname=$itf
set network.wan.proto=dhcp
EOF
uci commit network
