#!/bin/sh /etc/rc.common
# uhub launcher

UHUB=/usr/local/bin/uhub 
USE_PROCD=1
start_service() {
  procd_open_instance
  procd_set_param command $UHUB
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_set_param file /etc/uhub/uhub.conf
  procd_set_param stdout 1
  procd_close_instance

}
